# Generated by Django 3.1.1 on 2021-05-31 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Image')),
                ('about_title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Addpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Image')),
                ('pc_title', models.CharField(max_length=100, verbose_name='Title')),
                ('pc_desription', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Addpic',
            },
        ),
        migrations.CreateModel(
            name='Addpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addpost_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('addpost_description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Addpost',
            },
        ),
        migrations.CreateModel(
            name='Mudia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Image')),
                ('pst_title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Mudia',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_img', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('add_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('listing_type', models.CharField(max_length=40, null=True, verbose_name='Listing Type')),
                ('add_desription', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image')),
                ('port_title', models.CharField(max_length=100, verbose_name='Profile Title')),
                ('port_desription', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='blog Image')),
                ('blog_title', models.CharField(max_length=100, verbose_name='blog Title')),
                ('blog_desription', models.TextField(verbose_name='Description')),
                ('appear_home', models.CharField(choices=[('Feature', 'Appear on home'), ('No Feature', "Don't show on home"), ('', 'Please Choose')], default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blog',
            },
        ),
    ]
