# Generated by Django 3.1.1 on 2021-05-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpost',
            old_name='addpost_description',
            new_name='addpost_desription',
        ),
    ]
