# Generated by Django 3.1.1 on 2021-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='port_img',
            new_name='port_img1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='port_title',
            new_name='port_title1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title2',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title3',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title4',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title5',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title6',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
    ]
