# Generated by Django 3.1.1 on 2021-08-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210816_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_img7',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title7',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title8',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title'),
            preserve_default=False,
        ),
    ]
