# Generated by Django 3.1.1 on 2021-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210816_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='port_desription',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_img9',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image9'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_title9',
            field=models.CharField(default='img', max_length=100, verbose_name='Profile Title9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image4'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image5'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image6'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img7',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image7'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Profile Image8'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title1',
            field=models.CharField(max_length=100, verbose_name='Profile Title1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title2',
            field=models.CharField(max_length=100, verbose_name='Profile Title2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title3',
            field=models.CharField(max_length=100, verbose_name='Profile Title3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title4',
            field=models.CharField(max_length=100, verbose_name='Profile Title4'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title5',
            field=models.CharField(max_length=100, verbose_name='Profile Title5'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title6',
            field=models.CharField(max_length=100, verbose_name='Profile Title6'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title7',
            field=models.CharField(max_length=100, verbose_name='Profile Title7'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_title8',
            field=models.CharField(max_length=100, verbose_name='Profile Title8'),
        ),
    ]
